# Site settings
title: liyang's blog
email: 19198926@qq.com
description: "this is liyang's blog."
baseurl: ""
url: "http://liyang1221.github.io"
twitter_username: 
github_username:  liyang1221
# Build settings
markdown: kramdown
permalink: pretty