# Site settings
title: 明天，你好！
email: 19198926@qq.com
description: "copyright github && jekyll."
baseurl: ""
url: "http://rugbbyli.github.io"
twitter_username: 
github_username:  rugbbyli
# Build settings
pygments: true
mardown: redcarpet
