# Site settings
title: "Crazy Neptune"
url: "http://blog.oldrivers.cc"
highlighter: rouge
paginate: 10
author:
    name: RugbbyLi
    github: RugbbyLi
    email: rugbbyli@foxmail.com
    gitcafe: 
    twitter:
    facebook:
    googleplus:
    weibo: 
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

file_path: /files
img_path: /imgs
assets_path: /assets

sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name:                               # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

