# Site settings
title: 明天，你好！
email: 19198926@qq.com
description: "copyright github && jekyll."
baseurl: ""
url: "http://liyang1221.github.io"
twitter_username: 
github_username:  liyang1221
# Build settings
markdown: kramdown
permalink: pretty